kind: pipeline
type: docker
name: default

- name: Deploy GH Pages
  image: node
  pull: if-not-exists
  commands:
    - cd website
    - npm i
    - npm run publish-gh-pages-ci
  environment:
    GIT_USER: $DRONE_COMMIT_AUTHOR
    CURRENT_BRANCH: master
  when:
    branch:
    - master
