baseURL = "/"
languageCode = "en-us"
title = "CleverPush Developer Docs"
description = "CleverPush offers a REST API and various SDKs for Web Push and App Push Notifications"
Paginate = 4
publishDir = "docs"
[Params]
  RSSLink = ""
  author = "CleverPush" # add your company name
  github = "cleverpush" # add your github profile name
  twitter = "cleverpush_com" # add your twitter profile
  email = ""

[[menu.main]]
    name = "SDK Docs"
    weight = -100
    url = "/sdks/"
[[menu.main]]
    name = "API Reference"
    weight = -100
    url = "https://api.cleverpush.com"
    target = "_blank"
